@baseUrl = http://localhost:3000
@contentType = application/json
@token = {{token}}

### OBTENER TODOS LOS LIBROS
GET {{baseUrl}}/books
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### OBTENER UN LIBRO POR ID
GET {{baseUrl}}/books/2
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### CREAR UN NUEVO LIBRO 
POST {{baseUrl}}/books
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "title": "Firul",
  "isbn": "978-3-16-121547-0",
  "description": "Una novela de acción.",
  "publishedAt": "2023-05-15",
  "copies": 4,
  "copiesAvailable": 4,
  "categoryId": 1,
  "authorId": 2
}


### ACTUALIZAR UN LIBRO - MODIFICA SOLO LO ENVIADO
PATCH {{baseUrl}}/books/3
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "title": "Final - Actualizado",
  "copies": 12,
  "copiesAvailable": 11,
  "categoryId": 1,
  "description": "Edición corregida"
}

### ELIMINAR UN LIBRO
DELETE {{baseUrl}}/books/3
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
