@baseUrl = http://localhost:3000
@contentType = application/json
@token = {{token}}

### OBTENER TODAS LAS CATEGORIAS CON SUS LIBROS
GET {{baseUrl}}/categories
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### OBTENER UNA CATEGORIA CON ID CON SUS LIBROS
GET {{baseUrl}}/categories/2
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### CREAR UNA NUEVA CATEGORIA
POST {{baseUrl}}/categories
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "name": "Acción y Aventura",
  "description": "Categoría para libros de acción y aventura"
}

### ACTUALIZAR UNA CATEGORIA EXISTENTE
PATCH {{baseUrl}}/categories/2
Content-Type: {{contentType}} 
Authorization: Bearer {{token}}

{
  "name": "Aventura Épica",
  "description": "Categoría actualizada para libros de aventura épica"
}

### ELIMINAR UNA CATEGORIA
DELETE {{baseUrl}}/categories/2
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
